# reference: http://www.objc.io/issue-6/travis-ci.html

language: objective-c
before_install: pod install
script:
- xctool test -workspace GrowthKit.xcworkspace -scheme GrowthKit -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
